### ISSUE TITLE
Basic SEO optimisation

### ISSUE THREAD

**Issue by ajayesivan** [lumos-studio/leeway-website#64]
### Learnings
- [ ] Learn about SEO
- [ ] Importance of metatags like title, description, etc.
- [ ] Importance of using appropriate tags 

### Todo
- [ ] Add title & description
  - title: leeway - vehicle expense tracker
  - description: Track your vehicle fuel expenses with ease using leeway, the smart expense tracker. Get valuable insights on your mileage and cost per kilometer, and optimize your driving habits for maximum savings. Start saving time and money on your car expenses today.
- [ ] Update tags if required
